### ISSUE TITLE
vanilladpup64-9.2.10

### ISSUE THREAD

**Issue by sb-nipper** [vanilla-dpup/releases#2]
Hi, @dimtr  I have been looking for vanilladpup64-9.2.10 (and 32) which was not posted on schedule.

I looked on the action log and I see that it was built on schedule but the 
delete-older-releases@v2.0 deleted it again.  
Perhaps it did not parse the .9 to .10 correctly (I didn't examine)

Unless there are more items to put in this, could you re-run so it posts?

Thanks

**Comment by dimkr** [comment]
@sb-nipper Yes, there's a bug in delete-older-releases: it doesn't sort releases numerically, so it decides to delete release 10 instead of 9 (because `'1' < '9'`), when it's configured to keep only one release. I deleted 9.2.8 to make room for 9.2.11, so we'll just wait until Saturday.

**Comment by dimkr** [comment]
I took a second look and I think the problem is elsewhere. delete-older-releases receives the list of releases **sorted by commit**, but  9.2.9 and 9.2.10 were built using the **same** commit of vanilla-dpup/releases (although it's not the same commit in vanilla-dpup/woof-CE) and that probably caused 9.2.10 to appear before 9.2.9.

I'm not 100% sure how to fix this - maybe the best solution is a second, stable sort by release creation date.
