### ISSUE TITLE
Matching the major version number of the Debian release

### ISSUE THREAD

**Issue by dbohdan** [vanilla-dpup/releases#9]
First, cool live CD! I really like how the GUI resembles my favorite Puppy Linux theme from Puppy Linux 4.

When I first saw Vanilla Dpup, I thought for a moment that version 9 was based on Debian 9 "stretch" and outdated. I don't know your plans, but since the major version of Vanilla Dpup currently increments with the major version of the Debian release, you could use the same number as Debian. The next release would then be Vanilla Dpup 13.

**Comment by dimkr** [comment]
I started from 9 because it was appropriate at the time. I didn't want to start an "arms race" where all Puppy releases of the time use higher and higher version numbers to appear newer, more attractive and more competitive.

I'll definitely consider bumping to 13 when the right time arrives, though, because some Puppy releases now use time-based versioning or various kinds of meaningless versioning schemes. Closing this issue for now.
